package errtype

type Variation uint16

const (
	NoError Variation = iota
	Generic
	NullOrEmpty
	Null
	Empty
	Unknown
	IO
	ReadWrite
	InvalidInput
	InvalidOutput
	InvalidCondition
	EmptyString
	EmptySlice
	EmptyArray
	EmptyMap
	EmptyResult
	UnexpectedInteger
	UnexpectedString
	UnexpectedFloat
	UnexpectedValue
	UnexpectedArray
	UnexpectedArrayLength
	UnexpectedSliceLength
	UnexpectedMapLength
	UnexpectedInterface
	UnexpectedType
	UnexpectedPointer
	UnexpectedStatus
	UnexpectedFilePath
	UnexpectedDirectory
	UnexpectedCondition
	OutOfRangeValue
	OutOfRangeInteger
	OutOfRangeString
	OutOfRangeFloat
	OutOfRangeType
	OutOfRangeCategory
	OutOfRangeLength
	OutOfRangeStatus
	Warning
	DevelopmentEnvironment
	ProductionEnvironment
	TestEnvironment
	AssertionFailed
	EmptyStatus
	FileNotExist
	File
	FileWrite
	FileAccess
	FileAppend
	DirectoryNotExist
	Directory
	DirectoryAccess
	Execution
	Process
	LockFailed
	EmptyContent
	EmptyFile
	EmptyDirectory
	NotContainsExpectation
	ContainsExpectation
	EqualExpectation
	NotEqualExpectation
	LessThanExpectation
	LessThanEqualsExpectation
	GreaterThanExpectation
	GreaterThanEqualsExpectation
	NotEmptyFile
	Math
	Calculation
	Conversion
	ConversionValueToString
	ConversionValueToInteger
	ConversionValueToFloat
	ConversionValueToArray
	ConversionValueToSlice
	ConversionValueToMap
	ConversionValueToInterface
	ConversionValueToStruct
	ConversionValueToPointer
	MathDivide
	Between
	NotBetween
	NotSupportParameter
	NotSupportParameters
	NotSupportFunction
	NotSupportFunctions
	NotSupportInjections
	NotSupportValue
	NotSupportOperatingSystem
	NotSupportArchitecture
	NotSupportOsVersion
	NotSupportGroups
	NotSupportInWindows
	NotSupportInLinux
	NotSupportInMac
	NotSupportInUnix
	NotSupportInAndroid
	NotSupportVersion
	UnexpectedVersion
	NotImplemented
	FileOrDirectoryRelatedExecution
	SymbolicLink
	CommandExecution
	CommandExecutionNotFound
	FileInfo
	InvalidDefaultSwitchCase
	NotSupportedOption
	CastingFailed
	EmptyFilePath
	UnexpectedAccessToResource
	UnexpectedAccessRequest
	FailedAccessRequest
	RequestFailed
	UnexpectedRequest
	UnexpectedTry
	RetryExceed
	UnexpectedRetry
	FailedRetry
	FailedProcess
	CannotGrantPermission
	PermissionIssue
	PermissionNotFound
	PermissionFailed
	AccessRequestFailed
	UnAuthorizedAccess
	ResourceFreezeCannotAccess
	DisposedResourceCannotAccess
	FinalizedResourceCannotAccess
	FileMovedOut
	PolicyRelated
	PolicyFailed
	PolicyRequestRestricted
	FatalError
	WarningError
	SystemDamaged
	DiagnosticFailed
	UnexpectedDiagnostic
	AnalysisFailed
	RecurringProcessFailed
	Step1Failed
	Step2Failed
	Step3Failed
	Step4Failed
	Step5Failed
	Step6Failed
	Step7Failed
	Step8Failed
	StepFailed
	NextStepFailed
	PreviousStepFailed
	FinalStepFailed
	CompletionFailed
	CompileFailed
	SearchFailed
	QueryFailed
	DatabaseOperationFailed
	UIOperationFailed
	SynchronizationFailed
	ParsingFailed
	SyntaxFailed
	ExternalToolFailed
	CommandLineFailed
	CommunicationFailed
	GarbageCollectionFailed
	CreationRequestFailed
	ReadFailed
	EditFailed
	SaveFailed
	DeleteFailed
	ReadRequestFailed
	EditRequestFailed
	SaveRequestFailed
	DeleteRequestFailed
	CrudOperationFailed
	NetworkIssue
	NetworkOffline
	AdapterDisconnected
	Disconnected
	Offline
	Online
	Connection
	Connected
	TranspileFailed
	NginxParsingFailed
	ApacheParsingFailed
	EndSyntaxWrong
	BracketsMissing
	WrongSyntax
	StartSyntaxWrong
	TokenMissing
	Missing
	IntegrityBroken
	DataIntegrityLost
	MappingFailed
	CountFailed
	RemoveFailed
	NotAsExpected
	Unexpected
	CorruptedData
	NotFound
	Found
	Encoding
	Decoding
	Marshalling
	Unmarshalling
	InvalidProcess
	NotFoundProcess
	Chmod
	ChmodInvalid
	ChmodApplyFailed
	ExistingChmodReadFailed
	ChownIssue
	ChownUserOrGroupApplyIssue
	Permission
	Authorization
	AuthorizationFailed
	AuthorizationFailedToSave
	InstructionUndefined
	InstructionMustExist
	UnexpectedDefinition
	BashScriptIssue
	ShellScriptIssue
	PerlScriptIssue
	PythonScriptIssue
	BashScriptRunningProcessFailed
	ShellScriptRunningProcessFailed
	ScriptRunningFailed
	PowershellIssue
	CmdIssue
	PathStatusCannotRead
	FileRead
	FilesRead
	WriteFiles
	PathIssue
	PathNotFound
	PathExists
	InvalidPath
	PathRelatedIssue
	PathSyntaxIssue
	PathHasInvalidDataOrNilData
	RequestResourceNonExist
	ResourceMutating
	ReadOnlyExpected
	Env
	EnvironmentVariable
	EnvironmentVariableExist
	EnvironmentVariableNotExist
	EnvironmentVariableModify
	EnvPath
	LookupIssue
	IntConvertIssue
	FloatConvertIssue
	StringConvertIssue
	StringToIntConvertIssue
	StringToFloatConvertIssue
	StringToExpectedConvertIssue
	InterfaceToExpectedConvertIssue
	StringToStringConvertIssue
	ZippingFailed
	CompressingFailed
	CompressingIssue
	DecompressingIssue
	DecompressingFailed
	InstructionIssue
	EmptyCollection
	DictionaryNotContainsKey
	KeyNotExist
	ChangeDirectoryFailed
	CmdOnceFailed
	CmdOnceRunningIssue
	Invalid
	InvalidRequest
	InvalidData
	SystemRelated
	OsRelated
	OperatingSystemInternal
	SystemUser
	SysUserInvalid
	SysGroupInvalid
	CommandLineExecution
	NotFoundData
	NotFoundObject
	NotFoundItems
	NotFoundGroup
	NotFoundName
	InvalidId
	InvalidName
	InvalidIdentifier
	InvalidDir
	BashScriptRunning
	BashScriptFailed
	ShellScriptFailed
	PathInfoFailed
	StatFailed
	PathStatFailed
	StatusInvalid
	PathMissingOrInvalid
	PathMismatch
	Mismatch
	MismatchStatus
	MismatchRequest
	MismatchExpectation
	RwxMismatch
	ChmodMismatch
	DataMismatch
	OutOfSync
	ExpectationFailed
	TestFailed
	CreateDirectoryFailed
	RenameFailed
	RenameFileFailed
	RenamePathFailed
	CreatePathFailed
	DeletePathFailed
	ModifyDataFailed
	MissingPathsOrInvalidPaths
	Copy
	PathCopy
	Move
	PathMove
	Append
	Prepend
	PathExpand
	PathReadDir
	Remove
	Write
	LineIssue
	LinesIssue
	CollectionIssue
	ValidationFailed
	Delete
	DeletePath
	DeletePaths
	WriteFailed
	CreatePath
	NewPath
	Network
	NetPlan
	HostName
	ResolveIssue
	Sync
	ConflictIssue
	MergeIssue
	NonSync
	Binding
	MVVMIssue
	DesignIssue
	QuotationMissing
	RegexIssue
	RegexValidationIssue
	CannotApplyInstruction
	InstructionFormatIssue
	InstructionFormatMissingElementIssue
	FileSystemInstructionFailed
	EthernetInstructionFailed
	CronTabsInstructionFailed
	DatabaseInstructionFailed
	MySqlIssue
	PostgreSqlIssue
	LightSpeedParsingIssue
	LightSpeedSyntaxIssue
	SemicolonMissing
	ColonMissing
	EqualMissing
	ExpectationMismatch
	StringValidationMismatch
	BooleanValidationMismatch
	IntegerValidationMismatch
	FloatValidationMismatch
	StatusValidationMismatch
	RegexValidationMismatch
	ClosingError
	FileClosing
	DeferError
	MismatchValidation
	ContentValidationFailed
	CommandLineValidationFailed
	IniParsingFailed
	PsqlParsingFailed
	HbaParsingFailed
	ConfFileParsingFailed
	RegexCompiledFailed
	ChmodReadWriteFailed
	ChmodValidationFailed
	Validation
	ValidationMismatch
	TypeIssue
	DirIssue
	ApplyFailed
	ExecuteFailed
	UnixFileSystemIssue
	DatabaseIssue
	DatabaseReadIssue
	DatabaseAuthenticationFailed
	DatabaseQueryFailed
	EqualityCheckerFailed
	ComparisonMismatch
	ComparisonFailed
	ComparisonMethodFailed
	YamlParsingFailed
	YamlWritingFailed
	YamlReadFailed
	YamlSyntaxIssue
	YamlFileEmpty
	ConfFileEmpty
	JsonSyntaxIssue
	IniSyntaxIssue
	ConfSyntaxIssue
	FileSystemPermissionIssue
	LinesOrderMismatch
	LineIndexValidationFailed
	PathStat
	NoConditionMatchingAsPerExpectation
	AnyOfConditionShouldMatch
	AnyOfConditionShouldMatchForCreation
	AnyOfConditionShouldMatchForParsing
	AnyOfConditionShouldMatchForSelecting
	AnyOfConditionShouldMatchForWriting
	AnyOfConditionShouldMatchForReading
	AnyOfConditionShouldMatchForStatus
	AnyOfConditionShouldMatchForValue
	AppendFailed
	PrependFailed
	AddNewFailed
	NewFailed
	IncorrectData
	KeyMismatch
	ValueMismatch
	KeyValueNotFound
	KeyNotFound
	IdNotFound
	IdentifierNotFound
	IdentifierEmpty
	IdEmpty
	KeyEmpty
	KeyNotFoundInMap
	MapNotContainsExpectedKey
	FileInfoEmptyOrNil
	Apache
	CashBin
	CronTabs
	Dovecot
	Environment
	Ethernet
	Exim4
	InstallPackage
	LightSpeed
	LightSpeedParsing
	LightSpeedConfiguration
	LightSpeedBroken
	MySql
	PostgreSql
	PowerDns
	PureFtp
	Scoping
	OperatingSystemGeneral
	OperatingSystemRelated
	SSL
	SSH
	PhpFpm
	PhpAdmin
	OperatingSystemRepositoryIssue
	CoreConfigIssue
	InstructionNotSupportedInOperatingSystem
	InstallInstructionNotSupportedInOperatingSystem
	DockerNotSupport
	MethodNotSupportedInDocker
	MethodNotSupportedInOs
	InvalidOption
	InvalidSelection
	InvalidOptionForFunction
	Defined
	DefinedEmpty
	NotDefined
	DefinedUninitialized
	AlreadyDefined
	CaseMismatch
	NoCaseMatch
	Mutex
	Lock
	WaitGroupIssue
	UnAuthorized
	Hash
	HashCrypto
	Md5
	Sha1
	Sha256
	Sha512
	CheckSum
	CheckSumMismatch
	DuplicateIssue
	StringCorrupted
	DataCorrupted
	StatusCorrupted
	CheckSumCorrupted
	DeferIssue
	Undefined
	UnInitialized
	Unmapped
	InvalidInstruction
	Default
	FileOpen
	FileOpenOrRead
	FileCreate
	FileDelete
	FileEdit
	FilePrepend
	FileCrud
	DatabaseCrud
	RecordCreate
	RecordSave
	RecordEdit
	RecordIdMissing
	RecordPrimaryKeyMissing
	RecordForeignKeyMissing
	RecordDelete
	ObjectDelete
	ObjectInsert
	OrmInsert
	OrmCreate
	OrmEdit
	OrmSave
	OrmDelete
	UnChanged
	FileUnChanged
	FileLocked
	FilePermissionIssue
	FileInvalid
	FileInvalidOrMissing
	Open
	FileExpand
	Seek
	Commit
	FileSync
	FileCommit
	DataCommit
	RecordCommit
	StatusCommit
	DependencyIssue
	DependencyApiIssue
	CircularDependency
	DependencyNotFound
	DependencyMissing
	PackageMissing
	IdentifierMissing
	IdentifierValidationFailed
	KeyValidationFailed
	IdValidationFailed
	SectionValidationFailed
	GroupValidationFailed
	TypeValidationFailed
	HeaderValidationFailed
	InstructionValidationFailed
	LineNotFound
	SectionNotFound
	TypeNotFound
	ItemNotFound
	ItemMissing
	CategoryNotFound
	HeaderNotFound
	RootNotFound
	MapNotFound
	DataNotFound
	RecordNotFound
	RecordMissing
	KeyMissing
	RootMissing
	SectionMissing
	IdMissing
	HeaderMissing
	RequestHeaderMissing
	RequestDefinitionMissing
	TypeMissing
	GroupMissing
	DataMissing
	StatusMissing
	InstructionMissing
	ElementMissing
	ValueOrValuesMissing
	InstructionRootElementMissing
	InstructionNotDefined
	RecordInsert
	RecordUndefined
	RecordNotInitialized
	NotInitialized
	RequestValidationFailed
	HtmlValidationFailed
	TagValidationFailed
	JsonValidationFailed
	YamlValidationFailed
	ConfigValidationFailed
	DataUnordered
	RecordUnordered
	ValueOrValuesUnordered
	ItemsUnordered
	PowerDnsAddFailed
	PowerDnsEditFailed
	PowerDnsDomainOrZoneMissing
	PowerDnsUpdateFailed
	PowerDnsRecordResourceIssue
	PowerDnsRecordResourceCreateIssue
	PowerDnsRecordResourceDeleteIssue
	PowerDnsRecordResourceMissing
	PureFtpPermissionIssue
	PureFtpCrudIssue
	PureFtpUserCreateFailed
	PureFtpUserMissing
	PureFtpUserEditFailed
	PureFtpConfigEditFailed
	PureFtpConfigParsingIssue
	PureFtpConfigMissing
	LengthMismatch
	Exim4ConfigIssue
	Exim4UserIssue
	Exim4UserCreateIssue
	Exim4UserEditIssue
	Exim4UserDeleteIssue
	Exim4ConfCrudIssue
	Exim4ConfDeleteIssue
	Exim4ConfCreateIssue
	NotValidDirectory
	NotValidFile
	ServiceNotWorkingProperly
	OperatingSystemServiceNotWorkingProperly
	ServiceFailedToReceiveStatus
	ServiceInvalid
	UnknownService
	ServiceDead
	ServiceNotRunning
	ServiceDeadButPidExist
	SystemDOrSystemCtlMissing
	ServiceStatusCodeMismatch
	ExitCodeMismatch
	StatusMismatch
	UpdateFailed
	DbUpdateFailed
	DbCreateFailed
	DbEditFailed
	DbDeleteFailed
	DbCrudFailed
	DbLocked
	DbFileMissing
	RedisCrudFailed
	RedisUpdateFailed
	RedisEditFailed
	RedisDeleteFailed
	RedisCreateFailed
	RedisNullCmd
	RedisNotAvailable
	RedisConnectionIssue
	RedisNullValue
	RedisAdd
	RedisList
	RedisMap
	RecordUpdateFailed
	RecordEditFailed
	RecordDeleteFailed
	RecordCreationFailed
	DbRecordNotFound
	ParentDirCreateFailed
	DbMigration
	Migration
	VersionIssue
	ConversionFailed
	ConversionInterfaceToSpecificStruct
	StructureIntegrityIssue
	CachingIntegrityIssue
	IntegrityIssue
	ChownCopyFailed
	ChmodCopyFailed
	SnapshotFailed
	SnapshotIndexNotFound
	SnapshotNotFound
	SnapshotKeyNotFound
	BackupNotFound
	BackupKeyNotFound
	BackupDbRecordMissing
	BackupDbRecordNotFound
	SnapshotDbRecordMissing
	SnapshotDbRecordNotFound
	DbRecordKeyNotFound
	IndexInvalid
	IndexIssue
	IndexOutOfRange
	CompileErrors
	RedisKeyNotFound
	RedisIssue
	RedisCrud
	RedisDataMissing
	RedisRelationRecordMissing
	RedisNotRunning
	RedisIntegrityLost
	RedisSeedingDataMissing
	RedisRetrieveRecordIssue
	RedisUnknownIssue
	RedisConnectionLost
	RedisKeyAlreadyExist
	RedisDataStateMissing
	RedisRecordStatusMissing
	RedisWriteFailed
	RedisReadFailed
	RedisRecordMismatch
	DbRecordMismatch
	Critical
	CriticalData
	CriticalStatus
	DomainMissing
	ServerMissing
	ServerBlockIssue
	ServerState
	ServerStateUnknown
	ServerStateCorrupted
	LastKnowStateIssue
	ServerIdCorrupted
	IdCorrupted
	ServerUndefined
	SiteUndefined
	SiteMissing
	SiteIdMissing
	SubdomainMissing
	SslIssue
	SslMissing
	SslInvalid
	SslExpired
	SslMismatch
	SslDryRunFailed
	SslRenewFailed
	Challenge
	ChallengeIssue
	SslChallengeIssue
	DnsChallengeIssue
	HttpChallengeIssue
	HttpsChallengeIssue
	TlsSniChallengeIssue
	TlsAlpnChallengeIssue
	CAChallengeIssue
	DomainMismatch
	SiteContentMismatch
	ServerContentMismatch
	ContentMismatch
	AlreadyExist
	RecordAlreadyExist
	ContentAlreadyExist
	AlreadyPersist
	InvalidUsername
	UsernameMissing
	UsernameEmpty
	UserNotFound
	UserMismatch
	Banned
	Disabled
	AccountDisabled
	AccountSuspended
	Suspended
	UserSuspended
	RoleSuspended
	ContentDisabled
	ContentBlocked
	Blocked
	RecordBlocked
	RoleRemoved
	RightsRevoked
	RightsRemoved
	UserBanned
	UserRestricted
	UserRemoved
	RecordRemoved
	AccessRights
	AccessRightsDeny
	UserManagementIssue
	SuspiciousBehaviour
	Rights
	RoleIssue
	RoleInheritanceDenyPermission
	User
	UserRoleInvalid
	RoleInvalid
	UserHaveNoRights
	RoleMissing
	UserRoleDenyPermission
	PersistentRecordMismatch
	UnSync
	BlockIssue
	BlockSyntaxIssue
	BlockNotFound
	SubdomainNotFound
	SubdomainMismatch
	DomainOrSubdomainAlreadyAssigned
	ResourceAlreadyAssigned
	RecordAlreadyAssigned
	PathAlreadyAssigned
	FileAlreadyAssigned
	DirAlreadyAssigned
	ServerAlreadyAssigned
	SiteAlreadyAssigned
	OwnerDifferent
	Username
	UsernameAlreadyExist
	NameMismatch
	IdMismatch
	RequestInvalid
	ResponseInvalid
	SpecUndefined
	ValueNotFound
	QueryInvalid
	QueryEmpty
	FieldMissing
	FieldsMissing
	QueryParameterInvalid
	QueryParameterEmpty
	RequestParameterEmpty
	Response
	ResponseExpectedParameterMissing
	ArgumentInvalid
	ArgumentEmpty
	ContentEmpty
	ContentDefined
	TraverseIssue
	RecursionIssue
	RecursionMaxDept
	RecursionInvalidState
	NodeInvalid
	Level
	MaxDepth
	MaxLimit
	DirWalk
	PathRecursiveTravel
	DirNotFound
	FileNotFound
	ChownMismatch
	ManyNullOrEmpty
	RelatedRecordMissing
	ForeignKeyIssue
	PrimaryKeyIssue
	SubRecordNotFound
	SomeStatesMissing
	SomePathsInvalidOrPermissionIssue
	RelatedRecordExpected
	ExpectedKeyMissing
	ExpectedNameMissing
	ExpectedIdMissing
	ExpectedUserMissing
	ExpectedValueMissing
	ExpectedContentMissing
	ExpectedStatusMissing
	FileStateMismatch
	PathStateMismatch
	DirStateMismatch
	PathStateNotFound
	ExpectingDirButFile
	ExpectingFileButDir
	DirInvalidOrMissing
	UnsatisfyingCondition
	AsyncIssue
	FetchingFailed
	VersionConflict
	Conflict
	StatusConflict
	IdConflict
	NameConflict
	KeyConflict
	PrimaryKeyConflict
	ForeignKeyConflict
	Merge
	MergeConflict
	ProcessInvalid
	EmptyId
	EmptyUser
	EmptyPath
	EmptyDir
	EmptyResponse
	EmptyField
	EmptyRecords
	EmptyStates
	EmptyQuery
	EmptyRequest
	NoDiskSpace
	DiskSpace
	QuotaExpired
	DiskSpaceQuotaExpired
	LimitWarning
	MailBoxExpired
	MailQuotaExpired
	UserQuotaExpired
	Expired
	LimitExpired
	ContentExpired
	TokenExpired
	VersionExpired
	CacheExpired
	RefreshTokenExpired
	AuthTokenExpired
	RouteExpired
	FileStateExpired
	UserExpired
	AccountExpired
	Revoked
	SecurityIssue
	TaskFailed
	AsyncTaskFailed
	ParallelTaskIssue
	ApplicationMigrationFailed
	VersionMigrationFailed
	RecordMigrationFailed
	SeedingMigrationFailed
	AddOrUpdate
	CreateOrUpdate
	DeleteOrSkip
	Group
	GroupCrud
	GroupAddOrUpdate
	Status
	StatusCrud
	PasswordCrud
	PasswordIssue
	FileIssue
	StackOverflow
	TaskIdNotFound
	TaskCategoryNotFound
	CategoryMissing
	TaskMissing
	TaskNotFound
	ProcessNotFound
	HandlerMissing
	StateMismatch
	StateCorrupted
	Search
	History
	HistoryNotFound
	PackageNotFound
	InternetConnection
	PayloadCastingFailed
	PayloadIntegrity
	PayloadCategoryIssue
	PayloadEntityTypeIssue
	PayloadSubscriptionFailed
	PayloadIssue
	PayloadNotFound
	SubscriptionRelated
	SubscriptionInvalid
	NewCreationFailed
	NewOrCasting
	BytesNotFound
	CastingIssue
	Pipeline
	PipelineConstructionFailed
	PipelineCastingFailed
	LoggerFailed
	LoggerCastingFailed
	LoggerMismatch
	LoggerFailedToSave
	EntityFailed
	EntityNotFound
	EntityCastingFailed
	WithinRange // invert of OutOfRange
	OutOfRange
	RescheduleFailed
	ScheduleFailed
	ScheduleSaveFailed
	ScheduleRemoveFailed
	ScheduleEditFailed
	ScheduleRetryFailed
	ConvertFailed
	InjectionFailed
	DependencyInjectionFailed
	DependencyInjectionMissing
	MissingComponent
	CronFailed
	CronEditFailed
	CronSaveFailed
	CronRemoveFailed
	Shutdown
	Reboot
	JsonParseIssue
	JsonError
	Serialize
	Deserialize
	ReflectSetTo
	MaxError
)
